# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

version: '{build}'

environment:
  matrix:
    - nodejs_version: '10'
      platform: x86
    - nodejs_version: '12'
      platform: x86
install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php -i
  - SET PATH=C:\tools\php72\;%PATH%
  - SET PATH=C:\tools\php73\;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

build: off

matrix:
  fast_finish: true

test_script:
  - node --version && npm --version
  - npm test

cache:
  - 'node_modules -> appveyor.yml,package.json,package-lock.json'
